.PHONY: run install

PYTHON = python3
SCRIPT = reader.py
FOLDER_PATH ?= pdfs
SEARCH_TEXT ?= "default_search_text"  # Default search text

run:
	$(PYTHON) $(SCRIPT) $(folder_path) $(search_text)

install:
	$(PYTHON) -m pip install -r requirements.txt





